include: package:lints/recommended.yaml

# Additional stricter rules a crypto package should satisfy.
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_final_locals
    - prefer_single_quotes
    - unawaited_futures
    - unnecessary_parenthesis
